Fix information tab
vrodriguezf/deepvats pull request #120
Opened 2023-12-28 09:08 UTC by misantamaria

Information crashed
Fixed by moving logging messages and fixing ts_ar hash printing message

2023-12-30 17:34 UTC, vrodriguezf requested changes

2023-12-30 17:34 UTC, vrodriguezf commented on r_shiny_app/witc2024_8
¿Qué es esto?

2023-12-30 23:17 UTC, misantamaria commented
Los logs que estaba intentando sacar para guardar los tiempos. Reviso, que eso debería acabar fuera.Enviado desde Outlook para Android

2024-01-16 10:49 UTC, vrodriguezf commented on r_shiny_app/witc2024_8
Esto lo has quitado?

2024-01-16 15:52 UTC, misantamaria commented on r_shiny_app/witc2024_8
Eliminado. Eliminados también otros ficheros de logs/profvis.

2024-02-25 12:12 UTC, merged