Hotfix
vrodriguezf/deepvats pull request #125
Opened 2024-03-01 15:57 UTC by misantamaria

Hotfixes:
- cfg. -> cfg_. errata in 01_...
- data_fpath configuration in  config.ipybn force_artifact_config_sd2a
- Ensure data/wandb_artifacts for avoiding errors when executing 01-... the first time
- Selection point error for 1/2 projection points fixed
- Toy window size fixed in config.ipybn

2024-03-05 14:14 UTC, vrodriguezf requested changes

2024-03-05 14:14 UTC, vrodriguezf commented on nbs_pipeline/Notas.txt
remove this

2024-03-07 16:51 UTC, misantamaria commented
Fichero removido. He añadido el cambio del hook que pregunta por los yml 

- Un .sh que gestiona las preguntas etc. 
- Línea en entrypoint que añade linea en el pre-commit si no la tienes para ejecutar el .sh asociado al hook '¿has cambiado algun fichero de configuracion?'
- En caso de haber modificado algo te pregunta si estás o no seguro y puedes poner que sí para que lo suba, que no para que suba todo lo demás o cancelas y especificas lo concreto 

TODO 1: Posibles mejoras a futuro: Que deje elegir yml a yml
TODO2: Comprobar que funciona desde dentro del ./git.sh si se aprueba la rama de hooks . Este hook debería funcionar igualmente porque no tiene nada que ver con nbdev, es intrínseco de git. .git/hook/pre-commit

2024-03-14 11:38 UTC, vrodriguezf approved these changes

2024-03-14 11:38 UTC, vrodriguezf approved these changes

2024-03-14 11:57 UTC, vrodriguezf approved these changes

2024-03-14 11:57 UTC, merged